globals: ["@global"]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true

title_template: "tunji.io / %s"
og_image: /img/og_emma.png
author: S Tunji Turner
favicon: /img/favicon.jpg
description: Minimalist, designer, and UX developer
port: 8083

# OG image
origin: https://simple-blog.nuejs.org
og: /img/og.jpg

header:
  navigation:
    - ...from the mind, heart and soul of S Tunji Turner: /
    # - Let's Communicate: /contact/

footer:
  copyright:
    - ©tunji.io fortified by ©sight media lab. + ©soursop.: /

  social:
    - image: /img/twitter.svg
      url: //x.com/tipiirai
      alt: Twitter (X) profile
      size: 22 x 22

    - image: /img/github.svg
      url: //github.com/nuejs/
      alt: Github Projects
      size: 22 x 22
